# Generated by Django 3.1.6 on 2021-02-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
