# Generated by Django 3.1.4 on 2021-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('eventdate', models.DateTimeField(verbose_name='Data')),
                ('eventdescription', models.TextField()),
                ('event_type', models.CharField(choices=[('Virtual', 'Virtual'), ('Live', 'Live'), ('Hybrid', 'Hybrid')], max_length=50)),
            ],
        ),
    ]
