# Generated by Django 3.1.4 on 2021-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='banner',
            field=models.ImageField(null=True, upload_to='bannere'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdate',
            field=models.DateTimeField(verbose_name='data'),
        ),
    ]
