# Generated by Django 3.1.4 on 2021-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210208_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventdate',
            field=models.CharField(max_length=200),
        ),
    ]
