# Generated by Django 3.1.6 on 2021-02-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210211_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='bannere'),
        ),
    ]
