# Generated by Django 3.1.6 on 2021-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_events_eventagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventagenda',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdescription',
            field=models.TextField(default=''),
        ),
    ]
