# Generated by Django 3.1.6 on 2021-02-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210213_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app1.events'),
        ),
    ]
