# Generated by Django 3.1.6 on 2021-02-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210213_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=300)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('event_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app1.events')),
            ],
        ),
    ]
