# Generated by Django 3.1.6 on 2021-02-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
