# Generated by Django 3.1.6 on 2021-02-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='question',
            name='event_connected',
        ),
    ]
