# Generated by Django 3.1.6 on 2021-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20210214_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='short',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
