# Generated by Django 3.1.6 on 2021-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_events_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='short',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
