# Generated by Django 3.1.6 on 2021-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210215_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='short',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
