# Generated by Django 3.1.6 on 2021-02-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20210215_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='video_url',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
