# Generated by Django 3.1.6 on 2021-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_events_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='short',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
