# Generated by Django 3.1.6 on 2021-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20210216_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='short',
            field=models.CharField(default='uuid.uuid1', max_length=30, null=True, unique=True),
        ),
    ]
