# Generated by Django 3.1.6 on 2021-02-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20210216_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='short',
        ),
    ]
