# Generated by Django 3.1.6 on 2021-02-16 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_events_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 16, 23, 7, 18, 620657, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='eveniment',
            field=models.ForeignKey(default='orice', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app1.events'),
        ),
    ]
