# Generated by Django 3.1.6 on 2021-02-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('q1', models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Medium', 'Medium'), ('Insuficient', 'Insuficient')], max_length=100)),
                ('q2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=100)),
                ('comments', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.events')),
            ],
        ),
    ]
