# Generated by Django 3.1.6 on 2021-02-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='q3',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Medium', 'Medium'), ('Insuficient', 'Insuficient')], default='Yes', max_length=100, verbose_name="3. How would you rate the event's organization?"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='Yes', max_length=100, verbose_name='4. Would you attend other events organized online?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q5',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Medium', 'Medium'), ('Insuficient', 'Insuficient')], default='Yes', max_length=100, verbose_name='5. How to you rate the quality of the scientific content?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=100, verbose_name='1. Did you learn anything participating in this event?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Medium', 'Medium'), ('Insuficient', 'Insuficient')], max_length=100, verbose_name='2. How would you rate the quality of speakers?'),
        ),
    ]
