# Generated by Django 3.1.6 on 2021-02-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_auto_20210221_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(max_length=500, verbose_name='Comments and suggestions:'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='Yes', max_length=100, verbose_name='1. Did you learn anything participating in this event?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Medium', 'Medium'), ('Insuficient', 'Insuficient')], default='Yes', max_length=100, verbose_name='2. How would you rate the quality of speakers?'),
        ),
    ]
